name: Emoji Correction v.1.1
on:
  workflow_dispatch:
    inputs:
      file_pattern:
        description: 'File pattern to search (optional)'
        required: false
        default: '*.html'

permissions:
  contents: write

jobs:
  correct_emojis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Correct Emojis
        run: |
          cat << 'EOF' > correct_emojis.py
          import os
          import re
          from pathlib import Path
          
          def correct_emojis(content):
              modified = False
              
              # Pattern for whatsapp-floating and sms-floating
              # Look for any emoji after the domain/
              chat_pattern = r'(class="(?:whatsapp|sms)-floating".*?href="[^"]*/)[^-]*(-.*?")'
              if re.search(chat_pattern, content):
                  content = re.sub(chat_pattern, r'\1💬\2', content)
                  modified = True
              
              # Pattern for tlp-floating
              phone_pattern = r'(class="tlp-floating".*?href="[^"]*/)[^-]*(-.*?")'
              if re.search(phone_pattern, content):
                  content = re.sub(phone_pattern, r'\1📞\2', content)
                  modified = True
              
              return content, modified
          
          def process_files():
              modified_files = 0
              
              for html_file in Path('.').rglob('*.html'):
                  print(f"Checking file: {html_file}")
                  try:
                      with open(html_file, 'r', encoding='utf-8') as f:
                          content = f.read()
                      
                      new_content, was_modified = correct_emojis(content)
                      
                      if was_modified:
                          with open(html_file, 'w', encoding='utf-8') as f:
                              f.write(new_content)
                          print(f"✓ Corrected emojis in {html_file}")
                          modified_files += 1
                      else:
                          print(f"No corrections needed in {html_file}")
                  
                  except Exception as e:
                      print(f"Error processing {html_file}: {str(e)}")
              
              return modified_files
          
          if __name__ == '__main__':
              print("Starting emoji correction...")
              print("Current directory:", os.getcwd())
              print("Files found:", list(Path('.').rglob('*.html')))
              modified_count = process_files()
              print(f"\nOperation complete. Modified {modified_count} files.")
          EOF
          
          python3 correct_emojis.py
          
      - name: Check for changes and commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Correct emoji usage in floating buttons [automated]"
          
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
